drone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^fifa/', include('fifa.urls'))
]

fifa/urls.py
from django.conf.urls import url
from . import views

app_name = 'fifa'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^add_match$', views.add_match, name='add_match'),
    url(r'^getjson/', views.getjson)
]

fifa/models.py
from django.db import models
import datetime

class Team(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)

class Game (models.Model):
    team1 = models.CharField(max_length=100)
    team2 = models.CharField(max_length=100)
    date = models.DateField()

    def __str__(self):
        return str(self.team1)

fifa/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http import JsonResponse
import json
from .models import *

def home(request):
    games = Game.objects.all()
    d = dict()
    teams = set()       # A set of unique team name
    for g in games:
        teams.add(g.team1)
        teams.add(g.team2)
        date = g.date.strftime('%d %B %Y')  # Converting date into string
        if g.team1 in d:
            d[g.team1].append({g.team2: date})
        else:
            d[g.team1] = [{g.team2: date}]

        if g.team2 in d:
            d[g.team2].append({g.team1: date})
        else:
            d[g.team2] = [{g.team1: date}]

    matches2 = {}
    for team in d:
        matches2[team] = []
        for x in d[team]:
            for y in x:
                matches2[team].append(y)
    
    context = {"matches": d, "teams": teams}

    return render(request, 'fifa/index.html', context)


def add_match(request):
    if request.method == 'GET':
        teams_obj = Team.objects.all()
        all_countries = []
        for x in teams_obj:
            all_countries.append(x.name)
        context = {"all_teams": all_countries}
        return render(request, 'fifa/add.html', context)
    else:
        t1 = request.POST["team1"]
        t2 = request.POST["team2"]
        date = request.POST["date"]     #dd/mm/YYY
        date = format_date(date)        #YYYY-mm-dd
        game = Game.objects.create(team1 = t1, team2 = t2, date = date)
        game.save()
        return redirect(reverse('fifa:home'))


def getjson(request):
    d = dict()
    matches = Match.objects.all()
    for x in matches:
        rivals = []
        for y in x.followers.all():
            rivals.append(y.name)
        d[x.name] = rivals
    return JsonResponse(d)
    
def format_date(d):
    d = d.split('/')
    x = d[2] + '-' + d[0] + '-' + d[1]
    return x

fifa/templates/fifa/add.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'fifa/jquery.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'fifa/bootstrap.min.css' %}">
    <title>Add match</title>
</head>
<body>

    <a href="/fifa"><button class="btn btn-default" style="position: absolute; top: 0">Home</button></a>
    <center><h2>Create New Match</h2></center>
    <form action="" method="POST">
        {% csrf_token %}
        
        <div class="row" style="margin-top: 200px; width: 1000px; margin-left: 250px;">
            <div class="form-group col-lg-4">
                <label for="t1">Select Team 1</label>
                <select name="team1" class="form-control" id="team1">
                    {% for team in all_teams %}
                    <option value="{{team}}" >{{team}}</option>
                    {%endfor%}
            </select>
        </div>
            
            <br><br>
    
        <div class="form-group col-lg-4">
            <label for="t2">Select Team 2</label>
            <select name="team2" class="form-control" id="team2">
                {% for team in all_teams %}
                <option value="{{team}}" >{{team}}</option>
                {%endfor%}
            </select>
        </div>
            
        <div class="form-group col-lg-4">
            <label for="datebox">Enter Date</label><br>
            <input name="date" type = "text" id = "datebox" style="padding:5px" autocomplete="off" required>
            <button type="submit" class="btn btn-success offset-lg-1">Create</button>
        </div>

      </form>
    <script>

        $(function() {
           $( "#datebox" ).datepicker();
        });

    </script>

</body>
</html>

fifa/templates/fifa/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaflet project</title>
    <link rel="stylesheet" href="{% static 'fifa/leaflet.css' %}">
    <script src="{% static 'fifa/leaflet.js' %}"></script>
    <script src="{% static 'fifa/jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'fifa/bootstrap.min.css' %}">
    <style>
        #mapid{
            height: 700px;    
        }
        
        .button {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }

    </style>
</head>
<body>  
    <div class="row">
        <div class="col-lg-8">
            <div id="mapid"></div>
        </div>

        <div class="col-lg-4">
            <br>
            <h1>Track Your Team</h1>
            <div id="team_list" class="form-group">
                
                <select id="team" onchange="updateTeam(this)" class="form-control">
                        {% for team in teams %}
                        <option value="{{team}}">{{team | title}}</option>
                        {%endfor%}
                </select>
                
            </div>
            <div style="margin-top: 300px;" class="col-lg-offset-3"><a href="{% url 'fifa:add_match' %}"><a href="{% url 'fifa:add_match' %}"><button class="button">Create Match</button></a></div>
                <div style="margin-top: 300px;" class="col-lg-offset-3"><a href="{% url 'fifa:add_match' %}"></a></div>
            </div>
    </div>

    
    <script>
        var mymap = L.map('mapid').setView([20.5937, 78.9629], 2);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoia2hhbnNhYWxpbTEyIiwiYSI6ImNqaTVmODhvdTA0am0za21oYTh6M2JqeHYifQ.XXg7mBlXvaoMbTeOx3F6PQ', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: 'ypk.eyJ1Ijoia2hhbnNhYWxpbTEyIiwiYSI6ImNqaTVmODhvdTA0am0za21oYTh6M2JqeHYifQ.XXg7mBlXvaoMbTeOx3F6PQ'
    }).addTo(mymap);

        var current_layer = null
        var prev_layer = null

        var matches = {{matches|safe}} // # safe converts the dictionay into javascript object

        var coord = {
            "spain": [40.4637, 3.7492],
            "italy": [41.8719,12.5674],
            "france": [46.2276, 2.2137],
            "brazil": [14.2350, 51.9253],
            "japan": [36.2048, 138.2529],
            "germany": [51.1657, 10.4515],
            "russia": [61.5240, 105.3188],
            "turkey": [38.9637, 35.2433],
        }
    

        function getRivalsandDate(team){
            
            var obj = {}

            for (var i=0; i<matches[team].length; i++){
                o = matches[team][i]
                rv = Object.keys(o)[0]
                obj[rv] = o[rv]
            }
            return obj
        }
        
        function getCoords(place){
            return coord[place]
        }

        function getMarkers(obj){
            markers = []
            Object.keys(obj).forEach(function(key){
                c = getCoords(key)
                game_date = obj[key]
                marker = L.marker(c)
                cap_name = capital(key)
                popup_message = "<b>" + cap_name + "</b><br>" + game_date
                marker.bindPopup(popup_message)
                markers.push(marker)
            })
            return markers
        }
        
        function updateTeam(tag){
            team_name = tag.value
            prev_layer = current_layer
            rivals_obj = getRivalsandDate(team_name) //object
            markers = getMarkers(rivals_obj)
            current_layer = L.layerGroup(markers)
            mymap.removeLayer(prev_layer)
            mymap.addLayer(current_layer)
        }

        function initialiseMarkers(){
            defaultTeam = document.getElementById('team').value
            rivals_obj = getRivalsandDate(defaultTeam)
            markers = getMarkers(rivals_obj)
            current_layer = L.layerGroup(markers)
            mymap.addLayer(current_layer)
        }

        function capital(string){
            return string.charAt(0).toUpperCase() + string.slice(1)
        }
        
        initialiseMarkers()

    </script>
</body>
</html>


fifa/templates/fifa/tmp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>tmp</title>
</head>
<body>
    
</body>
</html>